### ISSUE TITLE
Decisions related to anaphora module

### ISSUE THREAD

**Issue by khannatanmai** [khannatanmai/apertium-anaphora#11]
1. can a LU which takes an antecedent be a noun itself?

**Comment by khannatanmai** [comment]
2. TL can have more than one word. So I'll have to change transfer.cc saying that instead of whats after the second slash, whats after the last slash is the reference. That's fine actually.

Doubt: When something with multiple words is an ANTECEDENT:
For eg., ^Presidente<n><f><sg>/President<n><f><sg>/Chairman<n><f><sg>/Chairperson<n><f><sg>/$

refered later in a pronoun. Which of these should I put? Can I put any of these or are these still ambiguous?
Update: Choice made to put FIRST word in TL as the antecedent.
@unhammer @ftyers

**Comment by unhammer** [comment]
Yes, President is antecedent there

**Comment by khannatanmai** [comment]
Work done on other repos:
apertium repo (anaphora branch) : https://github.com/apertium/apertium/tree/anaphora
Compare to master to see changes: https://github.com/apertium/apertium/compare/anaphora

apertium-eng-spa (anaphora-transfer branch) : https://github.com/khannatanmai/apertium-eng-spa/tree/anaphora-transfer
See PR to see changes: https://github.com/apertium/apertium-eng-spa/pull/13/files

@unhammer @ftyers

**Comment by khannatanmai** [comment]
Important Decision:
While finding the antecedent and resolving it, I will be using source language form, and ultimately in ref I will be putting the target language form.
