### ISSUE TITLE
First Person Pronouns

### ISSUE THREAD

**Issue by khannatanmai** [khannatanmai/apertium-anaphora#18]
While evaluating, the current method is changing my/our to his/their.
We need a method to only do Anaphora Resolution for third person pronouns as we decided earlier, because first and second are usually resolved in the real world.

However, the tagger isn't adding the person in the possessive determiners.
Is this a tagger issue to be fixed?
Or should we make a method of providing exceptions on which we don't want to apply the transfer rule?
Should this be done in my module or can this be written in t1x somehow?

@unhammer @ftyers

**Comment by unhammer** [comment]
Can you give an example? 

Den Tys 23 jul 2019, klokka 10:11, skreiv Tanmai Khanna:

**Comment by khannatanmai** [comment]
@unhammer  Yes look at the examples in the original comparison report I made, with the basic anaphora system: 
https://github.com/khannatanmai/apertium-anaphora/blob/master/Evaluation/Comparison_WordChanges.txt

**Comment by unhammer** [comment]
What's the original Spanish word? If the Spanish word doesn't specify number, then it's the responsibility of the anaphora module to find that number. 

Den Tys 23 jul 2019, klokka 21:40, skreiv Tanmai Khanna:

**Comment by khannatanmai** [comment]
Original Spanish: ¿Por qué no se han mejorado las escaleras desde **mi** accidente?
English Translation: Why they have not improved  the stairs from **my** accident?

Original Spanish: Si su decisión es que no podemos explicar **nuestro** voto, la acataré, pero no sin reservas.
English Translation: If his decision is that we can not explain **our** vote, will observe it, but no wholehearted.

Biltrans Output for mi and nuestro: (First Person)
^mío<det><pos><mf><sg>/my<det><pos><mf><sg>$
^nuestro<det><pos><m><sg>/our<det><pos><m><sg>$

Biltrans Output for su: (Third Person)
^suyo<det><pos><mf><sg>/his<det><pos><mf><sg>$

So they aren't the same as the third person pronouns, but the Biltrans input doesn't describe the number, i.e. doesn't distinguish between mi and su.

So we can add exceptions for some words or we can somehow modify the biltrans to add number to the analysis and then detect that. @unhammer @ftyers

**Comment by khannatanmai** [comment]
@unhammer @ftyers should I add the capability of adding exceptions to the rule in the ref file or can that be done in the transfer t1x file as well?

For eg., match "det.pos" except when it's "our" or "my".

Or, should I assume the tagger should tell me the person?

**Comment by unhammer** [comment]
Can the error propagate?

If it's a completely local error, then it's easy to solve in the transfer rule – e.g. if you have a transfer rule that checks the ref clip and would change "my" to "his", I'd be fine with just having the transfer rule check for that possibility first (transfer files already need to check such things other places). But if this my→his error can lead to later words also getting the wrong number, then the anaphora module needs to rule them out.

**Comment by khannatanmai** [comment]
Nope, it won't propagate. I'll modify the transfer rule and see the results.

**Comment by khannatanmai** [comment]
New Macro (Modified):
`<def-macro n="ref" npar="1"> <!-- anaphora -->`
`  <choose>`
`    <when>`
`      <test><not> <!-- ignore if it's first person, i.e. my or our -->`
`        <or>`
`          <equal><clip pos="1" side="tl" part="lem"/><lit v="my"/></equal>`
`          <equal><clip pos="1" side="tl" part="lem"/><lit v="our"/></equal>`
`        </or>`
`      </not></test>`
`      <choose>`
`EARLIER TRANSFER RULE`
`      </choose>`
`    </when>`
`  </choose>`
` </def-macro>`

Input Examples:

> ¿Por qué no se han mejorado las escaleras desde mi accidente?
> Si su decisión es que no podemos explicar nuestro voto, la acataré, pero no sin reservas.

Output:
> Why they have not improved  the stairs from **my** accident?
> If their decision is that we can not explain **our** vote, will observe it, but no wholehearted.

So it doesn't touch first person pronouns now. If there's a better solution, we can discuss it. @unhammer @ftyers
