### ISSUE TITLE
Antecedent Detection

### ISSUE THREAD

**Issue by khannatanmai** [khannatanmai/apertium-anaphora#4]
Write pseudocode for Antecedent Detection when input comes in a stream.
Report limitations and results.

**Comment by khannatanmai** [comment]
This will probably be done by CG now. So don't need to write individual codes for salience scores.

**Comment by unhammer** [comment]
Do what how by CG? Can you show the rules you'd use?

**Comment by khannatanmai** [comment]
@unhammer I'm not sure about the exact rules right now, but basically the saliency scores will be based on features like "if a noun is the subject", "if a noun is part of an adjunct", etc. and these can be detected by CG if I'm not wrong.

Is that true?

**Comment by unhammer** [comment]
Categorical features like that can be added by CG, yeah, though I'm not sure how easy it'd be to turn that into numbers and do the maths in CG

**Comment by khannatanmai** [comment]
@unhammer So the features can be added by CG and passed to my module. In the module, each will have a base score which can be modified based on the features added by CG.
Doing the math with the numbers in C and creating coreference chains shouldn't be hard.

**Comment by khannatanmai** [comment]
Since we decided we'll implement Mitkov's Algorithm first. Here are the factors that need to be detected:
Boosting Indicators
- First NPs in a sentence/clause (simple to implement)
- Lexical reiteration (sequence of NPs with the same head)
- Section heading preference (Seems to be specific for technical manuals? Not sure )
- Collocation pattern preference (Need to remember some patterns in a context, could be tricky)
- Immediate reference
- Sequential instructions (Again, specific for technical manuals it seems)
- Referential distance (May need clause identification or can work with sentences)

Impeding Indicators
- Indefiniteness (NPs which have indefinite articles - is this language independent? )
- Prepositional NPs (Can be detected - seem to be language independent)

IMPORTANT:
1. Need to know if NPs are detected in the pipeline already ( @unhammer @ftyers )
2. Will start implementing a scoring system which assigns 0 to everything
3. Once NPs are detected, I'll start coding the detection of the indicators mentioned above.

**Comment by khannatanmai** [comment]
Implemented Referential Distance:
Input:

> La niña come comida. El chico esta en la escuela. La silla está en el camino. El agua es mala. Las personas están en su habitación.

Output:
`^El<det><def><f><sg>/The<det><def><f><sg>/$ ^niño<n><f><sg>/girl<n><sg>/$ ^comer<vblex><pri><p3><sg>/eat<vblex><pri><p3><sg>/$ ^comida<n><f><sg>/lunch<n><sg>/food<n><sg>/$^.<sent>/.<sent>/$ ^El<det><def><m><sg>/The<det><def><m><sg>/$ ^chico<n><m><sg>/boy<n><sg>/$ ^este<prn><tn><f><sg>/this<prn><tn><mf><sg>/$ ^en<pr>/in<pr>/on<pr>/$ ^el<det><def><f><sg>/the<det><def><f><sg>/$ ^escuela<n><f><sg>/school<n><sg>/$^.<sent>/.<sent>/$ ^El<det><def><f><sg>/The<det><def><f><sg>/$ ^silla<n><f><sg>/chair<n><sg>/$ ^estar<vblex><pri><p3><sg>/be<vbser><pri><p3><sg>/$ ^en el camino<adv>/on the way<adv>/$^.<sent>/.<sent>/$ ^El<det><def><m><sg>/The<det><def><m><sg>/$ ^agua<n><f><sg>/water<n><sg>/$ ^ser<vbser><pri><p3><sg>/be<vbser><pri><p3><sg>/$ ^malo<adj><f><sg>/bad<adj><sint><f><sg>/$^.<sent>/.<sent>/$ ^El<det><def><f><pl>/The<det><def><f><pl>/$ ^persona<n><f><pl>/person<n><pl>/$ ^estar<vblex><pri><p3><pl>/be<vbser><pri><p3><pl>/$ ^en<pr>/in<pr>/on<pr>/$ ^suyo<det><pos><mf><sg>/his<det><pos><mf><sg>/person<n><pl>$ ^habitación<n><f><sg>/room<n><sg>/$^.<sent>/.<sent>/$^.<sent>/.<sent>/$`

Output of Antecedent List at the pronoun "his":
`id: wordform : score
2: girl<n><sg> : -2
4: lunch<n><sg> : -2
7: boy<n><sg> : -1
11: school<n><sg> : -1
14: chair<n><sg> : 0
19: water<n><sg> : 1
24: person<n><pl> : 2`

These scores are basically based on how close the noun is to the pronoun. (2 if the same sentence, 1 if the last sentence, and so on. Minimum score for ref distance is -2)

@unhammer @ftyers

**Comment by khannatanmai** [comment]
Doubt: Original Paper says that the NPs in the Previous Sentence are the most likely antecedents, whereas I've given highest score to NPs in the current sentences.

I feel that for possessive determiners like his/her/its, the more likely antecedents are in the current sentence whereas for pronouns like He/She/It, the more likely antecedent is in the previous sentence.

Can put separate scoring for both. Not sure

**Comment by khannatanmai** [comment]
Doubt #2: For Collocation Patterns, I need to match patterns with verbs and nouns to verbs and pronouns.
Eg. 1. , Press the button to switch it on. Now press it again.
Collocation Pattern: `<Press><The Button> & <Press><It>` hence 'it = the button'.

Eg. 2. John ate the pie and then he ate the fries.
Collocation Pattern: `<John><Ate> & <He><Ate>` hence 'John = He'.

Now the problem is, that the current approach is to take the input in a stream and stop at pronouns and resolve antecedent and then move on. However, for example 2, we need the word following the pronoun to create the collocation pattern.

Can I keep it in the buffer and print the pronoun with the resolved antecedent after I process a few words after it as well or will that mess up the input stream?

Or, do we give up on detecting these kind of collocation patterns?

@unhammer @ftyers Important Doubt!

**Comment by unhammer** [comment]
Buffering forwards a sentence or two is perfectly fine, CG already does this. But I would wait with this until we have several real-world examples. https://en.m.wikipedia.org/wiki/Pareto_principle#In_computing

**Comment by khannatanmai** [comment]
Ok I guess I'll wait before implementing this.
Interestingly, when the Mitkov algorithm was applied in Portuguese, they found that almost all the anaphors could be resolved using only three antecedent factors: 
1. Indefinite Pronouns: Assigned a -1 score
2. Prepositional NP: -1 if NP is part of a PP
3. Referential Distance: Score based on closeness to the pronoun.
(Paper: https://link.springer.com/content/pdf/10.1007%2F978-3-540-85980-2_6.pdf )

**Comment by khannatanmai** [comment]
Implemented these. Other ones will be in other issues.
