### ISSUE TITLE
Test Pipeline

### ISSUE THREAD

**Issue by khannatanmai** [khannatanmai/apertium-anaphora#8]
Now that transfer rules work with the modified code,
Need to have a pipeline ready to be tested.

**Comment by khannatanmai** [comment]
Pipeline works!
Report: https://github.com/khannatanmai/apertium-anaphora/blob/master/PipelineTest/PIPELINE%20TESTING.txt

Problem: Gender didn't change because in biltrans, girl is shown only as noun and singular, but we drop the gender.

Solution: If no gender in tl, take from sl?

@unhammer @ftyers

**Comment by unhammer** [comment]
Hm, I think the anaphora module might need some sort of config saying which tags to take from where – @ftyers ?

**Comment by khannatanmai** [comment]
About this we decided that we need a list of animate nouns (male and female) because taking nouns from sl also may not be correct in cases like spanish which have grammatical gender and arbitrary gender given to objects.
